### ISSUE TITLE
Media query flickering in Safari

### ISSUE THREAD

**Issue by Lalem001** [poole/poole#7]
When checking the responsiveness of Lanyon (in Safari 7.0), I noticed that the page would flicker between two media query states. So rapidly that it would consume about 80% of a single core.

I have traced the issue back to the following lines in poole's css:

``` css
html {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 16px;
  line-height: 1.5;
}
@media (min-width: 38rem) {
  html {
    font-size: 20px;
  }
}
```

It is not a stretch to think that Safari is evaluating the minimum width as 608px (16 \* 38) AND 760px (16 \* 20). Indeed, after a quick check, the issue does occur between those window sizes.

Clearly this is caused by the fact that REMs are being used, and that the HTML font-size is being changed by the mentioned media query.

The issue does not appear to occur in Chrome or Firefox.
